Feature/localstoragefavorites
PL-FE-SEP23-TeamMushrom/ProductCatalog pull request #58
Opened 2024-02-20 10:46 UTC by Barosz30

2024-02-20 16:24 UTC, Centmsn requested changes

2024-02-20 16:24 UTC, Centmsn commented on app/api/favorites/route.ts
> +  // req: NextRequest
do wywalenia?

2024-02-20 16:24 UTC, Centmsn commented on app/api/favorites/route.ts
> +const testarray: string[] = ["apple-iphone-7-plus-32gb-black", "apple-iphone-11-256gb-yellow", "apple-iphone-xs-64gb-spacegray", "apple-iphone-xr-64gb-red"]
![HehHuhGIF](https://github.com/PL-FE-SEP23-TeamMushrom/ProductCatalog/assets/65851661/9a78304b-6d72-48a3-b566-cf1b9e544861)

2024-02-20 16:24 UTC, Centmsn commented on app/favourites/page.tsx
> +      console.log(response)
do wywalenia?

2024-02-20 16:24 UTC, Centmsn commented on components/ProductCard/ProductCard.tsx
> +  const favorites = useLocalStorage('favorites');
Zróbmy jakiś obiekt z takimi stałymi (może być np. `/constants/localStorageKeys`) i używajmy ich wszędzie, zamiast stosować stringi:
```javascript
const LOCAL_STORAGE_KEYS = {
  FAVORITES: "FAVORITES",
  // other keys...
}
```

To samo podejście można zastosować do nazwa kolekcji z bazy danych

2024-02-20 16:24 UTC, Centmsn commented on hooks/useLocalStorage.ts
> +type Key = 'cart' | 'favorites'
Jak  już będzie ten obiekt z kluczami, to można z niego wziąć ten typ i mieć jedno źródło prawdy
```typescript
type LocalStorageKeys = keyof typeof LOCAL_STORAGE_KEYS
```

2024-02-20 16:24 UTC, Centmsn commented on hooks/useLocalStorage.ts
> +            console.log(`Added ${itemName} to favorites.`);
🙄

2024-02-20 16:24 UTC, Centmsn commented on hooks/useLocalStorage.ts
> +            console.log(`${itemName} is not in favorites.`);
Więcej console.logów!
![ChaosGIF](https://github.com/PL-FE-SEP23-TeamMushrom/ProductCatalog/assets/65851661/88303adf-6852-4c4f-8cf2-7706831374f1)

2024-02-21 08:38 UTC, mosowiecka approved these changes

2024-02-21 08:38 UTC, mosowiecka approved these changes

2024-02-21 08:57 UTC, Centmsn approved these changes

2024-02-21 09:05 UTC, merged